[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "async_python"
authors = [
    {name = "Ruslan Smirnov"},
]
description = "Repo for async python course"
readme = "README.md"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = []
